name: SonarCloud
on: [pull_request]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest #self-hosted
    env:
      SONAR_SERVER_URL: "https://sonarcloud.io"
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: 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
          SONAR_TOKEN: 52ee2f2305bbf4d3f233f1d02f16535c2722b92a
        - name: Run tests to generate coverage statistics
        run: |
          xcodebuild test \
          -project fantasize-ios.xcodeproj \
          -destination 'platform=iOS Simulator,name=iPhone 11,OS=16.0' \
          -derivedDataPath build \
          -enableCodeCoverage YES
      - name: Collect coverage into one XML report
        run: |
          bash xccov-to-generic.sh build/Logs/Test/*.xcresult/ > generic-coverage.xml
        run: |
          sonar-scanner \
        # --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}" \
          --define sonar.coverageReportPaths=generic-coverage.xml



# name: SonarCloud
# on: [pull_request]
# jobs:
#   sonarcloud:
#     name: SonarCloud
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
#       - name: SonarCloud Scan
#         uses: SonarSource/sonarcloud-github-action@master
#         env:
#           GITHUB_TOKEN: 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
#           SONAR_TOKEN: 52ee2f2305bbf4d3f233f1d02f16535c2722b92a